version: 2
updates:
  - package-ecosystem: "npm" # works for pnpm too
    directory: "/" # root of your repo
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: increase
